import { createFileRoute } from "@tanstack/react-router";
import { SiteNav } from "../components/SiteNav";
import { SiteFooter } from "../components/SiteFooter";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — ClerkNova" },
      { name: "description", content: "The terms that govern use of ClerkNova, the AI sales and support agent for Shopify stores." },
      { property: "og:title", content: "Terms of Service — ClerkNova" },
      { property: "og:description", content: "Terms that govern use of the ClerkNova service." },
    ],
  }),
  component: Terms,
});

function Terms() {
  return (
    <div className="min-h-screen bg-[#fffdfa] text-[#16130f]">
      <SiteNav />
      <main className="mx-auto max-w-3xl px-6 py-20 md:py-28">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#b9895b]">Legal</p>
        <h1 className="mt-3 text-4xl font-extrabold tracking-tight md:text-5xl">Terms of Service</h1>
        <p className="mt-3 text-sm text-[#6b6156]">Last updated: January 2026</p>

        <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-[#3a332b]">
          <Section title="1. Acceptance">
            By installing or using ClerkNova (the "Service"), you agree to these
            Terms of Service on behalf of yourself or the entity you represent
            ("Merchant"). If you do not agree, do not use the Service.
          </Section>

          <Section title="2. The Service">
            ClerkNova provides an AI agent that connects to a Merchant's Shopify
            store and communicates with End Users across website chat, WhatsApp,
            and voice. Outputs are generated by AI and may occasionally be
            inaccurate; the Merchant is responsible for reviewing rules, product
            data, and return policies configured in the Service.
          </Section>

          <Section title="3. Accounts and access">
            Merchants must provide accurate information, keep credentials
            confidential, and are responsible for activity under their account.
            We may suspend accounts that violate these Terms or applicable law.
          </Section>

          <Section title="4. Merchant responsibilities">
            <List items={[
              "Comply with Shopify, Meta / WhatsApp Business Platform, and telephony provider policies applicable to your use.",
              "Ensure you have the right to send messages and make calls to your End Users, including any required consent under local law.",
              "Configure accurate product, pricing, policy, and refund information; ClerkNova acts on the data you provide.",
              "Not use the Service for prohibited content, including unlawful, harassing, or deceptive communications.",
            ]} />
          </Section>

          <Section title="5. Fees">
            Pricing is presented at sign-up or in a separate order form. Fees are
            non-refundable except where required by law. Third-party costs
            (Shopify, Meta, telephony, LLM inference) may pass through as
            described at checkout.
          </Section>

          <Section title="6. AI output disclaimer">
            The Service uses large language models and can produce inaccurate or
            unexpected output. Merchants should test policies and rules and
            monitor conversations. ClerkNova does not warrant that AI output is
            accurate, complete, or fit for a particular purpose.
          </Section>

          <Section title="7. Data">
            Our processing of Merchant and End User data is described in the
            Privacy Policy, which is incorporated by reference.
          </Section>

          <Section title="8. Intellectual property">
            ClerkNova and its licensors retain all rights in the Service. Merchants
            retain ownership of their store data, brand assets, and conversation
            content, and grant ClerkNova a limited license to use them to operate
            the Service.
          </Section>

          <Section title="9. Third-party services">
            The Service integrates with third parties including Shopify, Meta /
            WhatsApp, telephony providers, and LLM providers. Their terms and
            policies apply to your use of those services, and outages or changes
            in those services may affect ClerkNova.
          </Section>

          <Section title="10. Warranty disclaimer">
            The Service is provided "as is" and "as available" without warranties
            of any kind, express or implied, including merchantability, fitness
            for a particular purpose, and non-infringement, to the maximum extent
            permitted by law.
          </Section>

          <Section title="11. Limitation of liability">
            To the maximum extent permitted by law, ClerkNova's aggregate liability
            arising out of or relating to the Service will not exceed the fees
            paid by the Merchant in the twelve months preceding the claim.
            ClerkNova will not be liable for indirect, incidental, consequential,
            special, or punitive damages.
          </Section>

          <Section title="12. Termination">
            Either party may terminate for convenience by providing notice.
            ClerkNova may suspend or terminate immediately for breach or misuse.
            Upon termination, access to the Service ends and data is deleted per
            the Privacy Policy.
          </Section>

          <Section title="13. Changes">
            We may modify these Terms. Material changes will be announced by email
            or in-product notice; continued use constitutes acceptance.
          </Section>

          <Section title="14. Contact">
            Questions? Email <a className="text-[#b9895b] underline underline-offset-2" href="mailto:support@clerknova.com">support@clerknova.com</a>.
          </Section>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-bold tracking-tight text-[#16130f]">{title}</h2>
      <div className="mt-3 space-y-3">{children}</div>
    </section>
  );
}

function List({ items }: { items: string[] }) {
  return (
    <ul className="list-disc space-y-2 pl-5 marker:text-[#b9895b]">
      {items.map((i) => <li key={i}>{i}</li>)}
    </ul>
  );
}
